
    /////////////////////////////////////////////////////////
	import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Enumeration;

import javax.swing.AbstractAction;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

import java.util.Random; 

	/**
	 *
	 * @author HP
	 */
	public class ShowQuickTestClass extends javax.swing.JFrame {

	    /**
	     * Creates new form NewJFrame
	     */
	    private  String[] arr1;
	    private  String[] arr2;
	    private  String[] arr3;
	    private  String[] arr4;
	    private String[] arr5;
	   
	    
	    public ShowQuickTestClass() {
	    	setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		    setPreferredSize(new Dimension(630, 650)); setUndecorated(true);
		    pack();
		    setLayout(null);
		    setVisible(true);
		    Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
			setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
	    	
	    	initComponents();
	        buttonGroup1.add(q1o1);
	        buttonGroup1.add(q1o2);
	        buttonGroup1.add(q1o3);
	        buttonGroup1.add(q1o4);
	       
	        buttonGroup2.add(q2o1);
	        buttonGroup2.add(q2o2);
	        buttonGroup2.add(q2o3);
	        buttonGroup2.add(q2o4);
	        
	        buttonGroup3.add(q3o1);
	        buttonGroup3.add(q3o2);
	        buttonGroup3.add(q3o3);
	        buttonGroup3.add(q3o4);
	        buttonGroup4.add(q4o1);
	        buttonGroup4.add(q4o2);
	        buttonGroup4.add(q4o3);
	        buttonGroup4.add(q4o4);
	        buttonGroup5.add(q5o1);
	        buttonGroup5.add(q5o2);
	        buttonGroup5.add(q5o3);
	        buttonGroup5.add(q5o4);
	        
	        
	        feedback1.setText("");
	        feedback2.setText("");
	        feedback3.setText("");
	        feedback4.setText("");
	        feedback6.setText("");
	        readword();
	        setoption();
	        addExitButtonOnMenuPanelMethod();
	    }
	    
		private void addExitButtonOnMenuPanelMethod(){
			Font font = new Font("Serif", Font.BOLD, 10);
			JButton button= new JButton(new AbstractAction("CLOSE") {
		         public void actionPerformed(ActionEvent e) {
		        	 dispose();
		         }
		      });
			button.setBounds(530,20,80,25);
			button.setBackground(Color.red);
			button.setFont(font);
			button.setForeground(Color.white);
			jPanel1.add(button);
		}
	    private void readword()
	    {
	        String filename = "C:/Users/ff/Downloads/gre.txt";
	        Random rand = new Random();
	        
	       ReadWordClass rr = new ReadWordClass();
	       int i1 = rand.nextInt(14)+1;
	       
	       
	       arr1=rr.read(i1, filename);
	       
	       int i2,k=rand.nextInt(14)+1;;
	       while(k==i1)
	       {
	       k=rand.nextInt(14)+1;
	       }
	       i2 = k;
	        
	       arr2=rr.read(i2, filename);
	       k=rand.nextInt(14)+1;
	        while(k==i1||k==i2)
	       {
	       k=rand.nextInt(14)+1;
	       }
	        int i3=k;
	        arr3=rr.read(i3, filename);
	         k=rand.nextInt(14)+1;
	   while(k==i1||k==i2||k==i3)
	       {
	       k=rand.nextInt(14)+1;
	       }
	        int i4 = k;
	        
	      arr4=rr.read(i4, filename);
	       k=rand.nextInt(14)+1;
	   while(k==i1||k==i2||k==i3||k==i4)
	       {
	       k=rand.nextInt(14)+1;
	       }
	       
	       int i5=k;
	        arr5=rr.read(i5, filename);
	       
	        
	                
	    }
	    /**
	     * This method is called from within the constructor to initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is always
	     * regenerated by the Form Editor.
	     */
	    @SuppressWarnings("unchecked")
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	    private void initComponents() {

	        buttonGroup1 = new javax.swing.ButtonGroup();
	        buttonGroup2 = new javax.swing.ButtonGroup();
	        buttonGroup3 = new javax.swing.ButtonGroup();
	        q2o12 = new javax.swing.JRadioButton();
	        jLabel5 = new javax.swing.JLabel();
	        feedback5 = new javax.swing.JLabel();
	        q2o10 = new javax.swing.JRadioButton();
	        q2o11 = new javax.swing.JRadioButton();
	        q2o9 = new javax.swing.JRadioButton();
	        buttonGroup4 = new javax.swing.ButtonGroup();
	        buttonGroup5 = new javax.swing.ButtonGroup();
	        jPanel1 = new javax.swing.JPanel();
	        jLabel1 = new javax.swing.JLabel();
	        q1o1 = new javax.swing.JRadioButton();
	        q1o2 = new javax.swing.JRadioButton();
	        q1o3 = new javax.swing.JRadioButton();
	        q1o4 = new javax.swing.JRadioButton();
	        q2o1 = new javax.swing.JRadioButton();
	        q2o2 = new javax.swing.JRadioButton();
	        jLabel2 = new javax.swing.JLabel();
	        q2o3 = new javax.swing.JRadioButton();
	        q2o4 = new javax.swing.JRadioButton();
	        submitBtn = new javax.swing.JButton();
	        feedback1 = new javax.swing.JLabel();
	        feedback2 = new javax.swing.JLabel();
	        q3o1 = new javax.swing.JRadioButton();
	        q3o2 = new javax.swing.JRadioButton();
	        jLabel3 = new javax.swing.JLabel();
	        q3o3 = new javax.swing.JRadioButton();
	        q3o4 = new javax.swing.JRadioButton();
	        feedback3 = new javax.swing.JLabel();
	        q4o1 = new javax.swing.JRadioButton();
	        q4o2 = new javax.swing.JRadioButton();
	        jLabel4 = new javax.swing.JLabel();
	        q4o3 = new javax.swing.JRadioButton();
	        q4o4 = new javax.swing.JRadioButton();
	        feedback4 = new javax.swing.JLabel();
	        q5o1 = new javax.swing.JRadioButton();
	        q5o2 = new javax.swing.JRadioButton();
	        jLabel6 = new javax.swing.JLabel();
	        q5o3 = new javax.swing.JRadioButton();
	        q5o4 = new javax.swing.JRadioButton();
	        feedback6 = new javax.swing.JLabel();

	        q2o12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
	        q2o12.setText("oiuadouwaoud");

	        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
	        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
	        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
	        jLabel5.setText("PREVARICATE");

	        feedback5.setText("abc");

	        q2o10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
	        q2o10.setText("efghi");
	        q2o10.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                q2o10ActionPerformed(evt);
	            }
	        });

	        q2o11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
	        q2o11.setText("123456");
	        q2o11.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                q2o11ActionPerformed(evt);
	            }
	        });

	        q2o9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
	        q2o9.setText("abcdef");

	        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
	        setBackground(new java.awt.Color(0, 0, 51));

	        jPanel1.setBackground(new java.awt.Color(102, 102, 0));

	        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
	        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
	        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
	        jLabel1.setText("PREVARICATE");

	        q1o1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
	        q1o1.setText("abcdef");
	        q1o1.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                q1o1ActionPerformed(evt);
	            }
	        });

	        q1o2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
	        q1o2.setText("to lie or deviate from the truth");
	        q1o2.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                q1o2ActionPerformed(evt);
	            }
	        });

	        q1o3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
	        q1o3.setText("qehqwkuehiuh");

	        q1o4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
	        q1o4.setText("qhqekeqih");

	        q2o1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
	        q2o1.setText("abcdef");

	        q2o2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
	        q2o2.setText("efghi");
	        q2o2.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                q2o2ActionPerformed(evt);
	            }
	        });

	        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
	        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
	        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
	        jLabel2.setText("PREVARICATE");

	        q2o3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
	        q2o3.setText("123456");
	        q2o3.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                q2o3ActionPerformed(evt);
	            }
	        });

	        q2o4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
	        q2o4.setText("oiuadouwaoud");

	        submitBtn.setText("Submit");
	        submitBtn.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                submitBtnActionPerformed(evt);
	            }
	        });

	        feedback1.setText("abc");

	        feedback2.setText("abc");

	        q3o1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
	        q3o1.setText("abcdef");

	        q3o2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
	        q3o2.setText("efghi");
	        q3o2.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                q3o2ActionPerformed(evt);
	            }
	        });

	        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
	        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
	        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
	        jLabel3.setText("PREVARICATE");

	        q3o3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
	        q3o3.setText("123456");
	        q3o3.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                q3o3ActionPerformed(evt);
	            }
	        });

	        q3o4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
	        q3o4.setText("oiuadouwaoud");

	        feedback3.setText("abc");

	        q4o1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
	        q4o1.setText("abcdef");
	        q4o1.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                q4o1ActionPerformed(evt);
	            }
	        });

	        q4o2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
	        q4o2.setText("efghi");
	        q4o2.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                q4o2ActionPerformed(evt);
	            }
	        });

	        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
	        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
	        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
	        jLabel4.setText("PREVARICATE");

	        q4o3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
	        q4o3.setText("123456");
	        q4o3.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                q4o3ActionPerformed(evt);
	            }
	        });

	        q4o4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
	        q4o4.setText("oiuadouwaoud");

	        feedback4.setText("abc");

	        q5o1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
	        q5o1.setText("abcdef");
	        q5o1.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                q5o1ActionPerformed(evt);
	            }
	        });

	        q5o2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
	        q5o2.setText("efghi");
	        q5o2.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                q5o2ActionPerformed(evt);
	            }
	        });

	        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
	        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
	        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
	        jLabel6.setText("PREVARICATE");

	        q5o3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
	        q5o3.setText("123456");
	        q5o3.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                q5o3ActionPerformed(evt);
	            }
	        });

	        q5o4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
	        q5o4.setText("oiuadouwaoud");

	        feedback6.setText("abc");

	        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
	        jPanel1.setLayout(jPanel1Layout);
	        jPanel1Layout.setHorizontalGroup(
	            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel1Layout.createSequentialGroup()
	                .addContainerGap()
	                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addGroup(jPanel1Layout.createSequentialGroup()
	                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
	                                .addComponent(q3o4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                                .addComponent(q3o3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                                .addComponent(q3o2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                                .addComponent(q3o1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
	                                .addComponent(q1o1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                                .addComponent(q1o2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                                .addComponent(q1o3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                                .addComponent(q1o4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                                .addComponent(q2o1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                                .addComponent(q2o2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                                .addComponent(q2o4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
	                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
	                                    .addGap(95, 95, 95)
	                                    .addComponent(feedback4, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
	                                .addComponent(q4o3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                                .addComponent(q4o1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                                .addComponent(q4o2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                                .addComponent(q4o4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	                            .addGroup(jPanel1Layout.createSequentialGroup()
	                                .addComponent(jLabel3)
	                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                                .addComponent(feedback3, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
	                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
	                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
	                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
	                                    .addGap(95, 95, 95)
	                                    .addComponent(feedback6, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
	                                .addComponent(q5o3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                                .addComponent(q5o1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                                .addComponent(q5o2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                                .addComponent(q5o4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
	                        .addContainerGap(30, Short.MAX_VALUE))
	                    .addGroup(jPanel1Layout.createSequentialGroup()
	                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                            .addGroup(jPanel1Layout.createSequentialGroup()
	                                .addComponent(jLabel1)
	                                .addGap(18, 18, 18)
	                                .addComponent(feedback1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
	                            .addGroup(jPanel1Layout.createSequentialGroup()
	                                .addGap(95, 95, 95)
	                                .addComponent(feedback2, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
	                            .addComponent(q2o3, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addComponent(submitBtn))
	                        .addGap(0, 0, Short.MAX_VALUE))))
	        );
	        jPanel1Layout.setVerticalGroup(
	            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel1Layout.createSequentialGroup()
	                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(feedback1))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addComponent(q1o1)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addComponent(q1o2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addComponent(q1o3)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addComponent(q1o4)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(feedback2))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addComponent(q2o1)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addComponent(q2o2)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addComponent(q2o3)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addComponent(q2o4)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
	                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(feedback3))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addComponent(q3o1)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addComponent(q3o2)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addComponent(q3o3)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addComponent(q3o4)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(feedback4))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addComponent(q4o1)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addComponent(q4o2)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addComponent(q4o3)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addComponent(q4o4)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(feedback6))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addComponent(q5o1)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addComponent(q5o2)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addComponent(q5o3)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addComponent(q5o4)
	                .addGap(18, 18, 18)
	                .addComponent(submitBtn)
	                .addContainerGap(51, Short.MAX_VALUE))
	        );

	        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
	        getContentPane().setLayout(layout);
	        layout.setHorizontalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	        );
	        layout.setVerticalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
	                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addGap(0, 0, Short.MAX_VALUE))
	        );

	        pack();
	    }// </editor-fold>                        

	    private void q1o1ActionPerformed(java.awt.event.ActionEvent evt) {                                     
	        // TODO add your handling code here:
	    }                                    
	public String getSelectedButtonText(ButtonGroup buttonGroup) {
	        for (Enumeration<AbstractButton> buttons = buttonGroup.getElements(); buttons.hasMoreElements();) {
	            AbstractButton button = buttons.nextElement();

	            if (button.isSelected()) {
	                return button.getText();
	            }
	        }

	        return null;
	    }
	public void setoption()
	{
	    jLabel1.setText(arr1[0]);
	    q1o1.setText(arr1[2]);
	     q1o2.setText(arr1[3]);
	      q1o3.setText(arr1[4]);
	       q1o4.setText(arr1[5]);
	       jLabel2.setText(arr2[0]);
	         q2o1.setText(arr2[2]);
	     q2o2.setText(arr2[3]);
	      q2o3.setText(arr2[4]);
	       q2o4.setText(arr2[5]);
	       jLabel3.setText(arr3[0]);
	        q3o1.setText(arr3[2]);
	     q3o2.setText(arr3[3]);
	      q3o3.setText(arr3[4]);
	       q3o4.setText(arr3[5]);
	       jLabel4.setText(arr4[0]);
	        q4o1.setText(arr4[2]);
	     q4o2.setText(arr4[3]);
	      q4o3.setText(arr4[4]);
	       q4o4.setText(arr4[5]);
	       jLabel6.setText(arr5[0]);
	        q5o1.setText(arr5[2]);
	     q5o2.setText(arr5[3]);
	      q5o3.setText(arr5[4]);
	       q5o4.setText(arr5[5]);
	    
	    
	}
	    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {                                          
	        // TODO add your handling code here:
	        String ans1 = arr1[1];
	        String userIp1 = getSelectedButtonText( buttonGroup1);
	        String ans2 = arr2[1];
	        String userIp2 = getSelectedButtonText( buttonGroup2);
	         String ans3 = arr3[1];
	        String userIp3 = getSelectedButtonText( buttonGroup3);
	        String ans4 = arr4[1];
	        String userIp4 = getSelectedButtonText( buttonGroup4);
	        String ans5 = arr5[1];
	        String userIp5 = getSelectedButtonText( buttonGroup5);
	        //System.out.println(userIp1);
	        int count= 0;
	        if(ans1.equals(userIp1)) {count++; feedback1.setText("Correct Answer");}
	        else feedback1.setText("Wrong! Answer: " + ans1);
	        if(ans2.equals(userIp2)) {count++; feedback2.setText("Correct Answer");}
	        else feedback2.setText("Wrong! Answer: " + ans2);
	        if(ans3.equals(userIp3)) {count++; feedback3.setText("Correct Answer");}
	        else feedback3.setText("Wrong! Answer: " + ans3);
	        if(ans4.equals(userIp4)) {count++; feedback4.setText("Correct Answer");}
	        else feedback4.setText("Wrong! Answer: " + ans4);
	        if(ans5.equals(userIp5)) {count++; feedback6.setText("Correct Answer");}
	        else feedback6.setText("Wrong! Answer: " + ans5);
	        
	        JOptionPane.showMessageDialog(null, "Total correct: " + count);
	        Enumeration<AbstractButton> enumeration =  buttonGroup1.getElements();
	while (enumeration.hasMoreElements()) {
	    enumeration.nextElement().setEnabled(false);
	}
	         Enumeration<AbstractButton> enum1 =  buttonGroup2.getElements();
	while (enum1.hasMoreElements()) {
	    enum1.nextElement().setEnabled(false);
	}
	 Enumeration<AbstractButton> enum2 =  buttonGroup3.getElements();
	while (enum2.hasMoreElements()) {
	    enum2.nextElement().setEnabled(false);
	}
	 Enumeration<AbstractButton> enum3 =  buttonGroup4.getElements();
	while (enum3.hasMoreElements()) {
	    enum3.nextElement().setEnabled(false);
	}
	Enumeration<AbstractButton> enum4 =  buttonGroup5.getElements();
	while (enum4.hasMoreElements()) {
	    enum4.nextElement().setEnabled(false);
	}
	        
	 //        else JOptionPane.showMessageDialog(null, "Wrong Answer! Correct is: " + ans1, "Wrong!", JOptionPane.ERROR_MESSAGE);
	    }                                         

	    private void q1o2ActionPerformed(java.awt.event.ActionEvent evt) {                                     
	        // TODO add your handling code here:
	    }                                    

	    private void q2o2ActionPerformed(java.awt.event.ActionEvent evt) {                                     
	        // TODO add your handling code here:
	    }                                    

	    private void q2o3ActionPerformed(java.awt.event.ActionEvent evt) {                                     
	        // TODO add your handling code here:
	    }                                    

	    private void q3o2ActionPerformed(java.awt.event.ActionEvent evt) {                                     
	        // TODO add your handling code here:
	    }                                    

	    private void q3o3ActionPerformed(java.awt.event.ActionEvent evt) {                                     
	        // TODO add your handling code here:
	    }                                    

	    private void q4o2ActionPerformed(java.awt.event.ActionEvent evt) {                                     
	        // TODO add your handling code here:
	    }                                    

	    private void q4o3ActionPerformed(java.awt.event.ActionEvent evt) {                                     
	        // TODO add your handling code here:
	    }                                    

	    private void q2o10ActionPerformed(java.awt.event.ActionEvent evt) {                                      
	        // TODO add your handling code here:
	    }                                     

	    private void q2o11ActionPerformed(java.awt.event.ActionEvent evt) {                                      
	        // TODO add your handling code here:
	    }                                     

	    private void q4o1ActionPerformed(java.awt.event.ActionEvent evt) {                                     
	        // TODO add your handling code here:
	    }                                    

	    private void q5o1ActionPerformed(java.awt.event.ActionEvent evt) {                                     
	        // TODO add your handling code here:
	    }                                    

	    private void q5o2ActionPerformed(java.awt.event.ActionEvent evt) {                                     
	        // TODO add your handling code here:
	    }                                    

	    private void q5o3ActionPerformed(java.awt.event.ActionEvent evt) {                                     
	        // TODO add your handling code here:
	    }                                    
	public void actionPerformed(ActionEvent e) {
	        if (e.getActionCommand().equals("Check")) {
	            System.out.println("Selected Radio Button: " + buttonGroup1.getSelection().getActionCommand());
	        }
	    }
	    /**
	     * @param args the command line arguments
	     */


	    // Variables declaration - do not modify                     
	    private javax.swing.ButtonGroup buttonGroup1;
	    private javax.swing.ButtonGroup buttonGroup2;
	    private javax.swing.ButtonGroup buttonGroup3;
	    private javax.swing.ButtonGroup buttonGroup4;
	    private javax.swing.ButtonGroup buttonGroup5;
	    private javax.swing.JLabel feedback1;
	    private javax.swing.JLabel feedback2;
	    private javax.swing.JLabel feedback3;
	    private javax.swing.JLabel feedback4;
	    private javax.swing.JLabel feedback5;
	    private javax.swing.JLabel feedback6;
	    private javax.swing.JLabel jLabel1;
	    private javax.swing.JLabel jLabel2;
	    private javax.swing.JLabel jLabel3;
	    private javax.swing.JLabel jLabel4;
	    private javax.swing.JLabel jLabel5;
	    private javax.swing.JLabel jLabel6;
	    private javax.swing.JPanel jPanel1;
	    private javax.swing.JRadioButton q1o1;
	    private javax.swing.JRadioButton q1o2;
	    private javax.swing.JRadioButton q1o3;
	    private javax.swing.JRadioButton q1o4;
	    private javax.swing.JRadioButton q2o1;
	    private javax.swing.JRadioButton q2o10;
	    private javax.swing.JRadioButton q2o11;
	    private javax.swing.JRadioButton q2o12;
	    private javax.swing.JRadioButton q2o2;
	    private javax.swing.JRadioButton q2o3;
	    private javax.swing.JRadioButton q2o4;
	    private javax.swing.JRadioButton q2o9;
	    private javax.swing.JRadioButton q3o1;
	    private javax.swing.JRadioButton q3o2;
	    private javax.swing.JRadioButton q3o3;
	    private javax.swing.JRadioButton q3o4;
	    private javax.swing.JRadioButton q4o1;
	    private javax.swing.JRadioButton q4o2;
	    private javax.swing.JRadioButton q4o3;
	    private javax.swing.JRadioButton q4o4;
	    private javax.swing.JRadioButton q5o1;
	    private javax.swing.JRadioButton q5o2;
	    private javax.swing.JRadioButton q5o3;
	    private javax.swing.JRadioButton q5o4;
	    private javax.swing.JButton submitBtn;
	    // End of variables declaration                   
	}
    